name: dota2_invoker_game
description: DOTA 2 Invoker practice game.

publish_to: 'none'

version: 1.5.0+26

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #State Management
  provider: ^6.1.2

  #Localization
  easy_localization: ^3.0.7

  #Icons
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8

  #Utils
  flutter_svg: ^2.0.10+1
  audioplayers: 
    git:
      url: https://github.com/tolgasozbir/audioplayers
  internet_connection_checker: ^2.0.0
  url_launcher: ^6.3.0
  auto_size_text: ^3.0.0
  flutter_fgbg: ^0.6.0
  tuple: ^2.0.2

  #.env
  flutter_config:
      git:
        url: https://github.com/egonm12/flutter_config.git

  #Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2

  #Firebase
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0
  firebase_remote_config: ^5.1.2
  firebase_analytics: ^11.3.2

  #Animation
  lottie: ^3.1.2
  splash: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  snappable_thanos: ^0.0.4
  flutter_animate: ^4.5.0

  #Widgets
  sleek_circular_slider: ^2.0.1
  reorderable_grid: ^1.0.10
  percent_indicator: ^4.2.3

  #Ads
  google_mobile_ads: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  #Lint
  very_good_analysis: ^6.0.0
  #Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.12


flutter:
  uses-material-design: true

  fonts:
    - family: Virgil
      fonts:
        - asset: assets/fonts/Virgil.ttf
          weight: 400

  assets:
    - .env

    - assets/lang/

    - assets/images/splash_images/
    - assets/images/qwe_gifs/
    - assets/images/misc/
    - assets/images/elements/
    - assets/images/spells/
    - assets/images/achievements/
    - assets/images/bosses/
    - assets/images/items/

    - assets/sounds/fail_sounds/
    - assets/sounds/gg_sounds/
    - assets/sounds/loading_sounds/
    - assets/sounds/spell_sounds/
    - assets/sounds/spell_sounds/cast_sounds/
    - assets/sounds/misc/
    - assets/sounds/ability_on_cooldown/
    - assets/sounds/not_enough_mana/
    - assets/sounds/shop_sounds/
    - assets/sounds/item_sounds/
    - assets/sounds/boss_sounds/warlock/
    - assets/sounds/boss_sounds/omniknight/
    - assets/sounds/boss_sounds/riki/
    - assets/sounds/boss_sounds/huskar/
    - assets/sounds/boss_sounds/templar/
    - assets/sounds/boss_sounds/anti_mage/
    - assets/sounds/boss_sounds/juggernaut/
    - assets/sounds/boss_sounds/blood_seeker/
    - assets/sounds/boss_sounds/blood_seeker/
    - assets/sounds/boss_sounds/drow_ranger/
    - assets/sounds/boss_sounds/axe/
    - assets/sounds/boss_sounds/pudge/
    - assets/sounds/boss_sounds/wraith_king/

    - assets/lottie/
    - assets/svg/
    - assets/icons/